"""Deleting one person may not cost another person one sample -- and she may
not be told she is gone while her vectors are on the disk.

THIS FILE EXISTS BECAUSE ONE BUG SURVIVED THREE FIXES. Every round aimed at
the route that had just been found, and every round the same outcome came back
through a different door:

* round 1: ``self.load()`` returned nothing on a mixed gallery, "no survivors"
  was inferred from an empty pool, and every generation holding her was
  destroyed -- taking the bystanders in them along;
* round 2: that path was fixed and the read-back that was supposed to catch it
  turned out to be inert, because it built its gallery with the DEFAULT model;
* round 3: a bystander could still lose an entire enrolment, destroyed by
  ``_prune()`` inside ``purge_label``'s own save, and the same call reported
  that generation as handled.

Three doors, one room. So these tests are not written against the doors. They
are written against the invariant that closes the room:

    NO FILE IS DESTROYED UNLESS THE EMBEDDINGS IT HELD, MINUS HERS, HAVE BEEN
    READ BACK FROM THE NEW GENERATION ON DISK.

Read back -- not inferred from a return value, not counted in memory, not
assumed from "the save did not raise". Anything that cannot be proved that way
is reported and LEFT ALONE, and the delete is not called complete.

And the other direction has to hold at the same time, or the fix is a
regression dressed as a fix: a delete may never report success while her data
is still on the disk. Each test below states which direction it is defending.

No test here opens a device, loads a model, or looks at, saves or asserts on
the content of any frame. Every vector is generated by this file.
"""
from __future__ import annotations

import numpy as np

from jarvis.facegallery import FaceGallery

from tests.test_faceenrol import base_vec, face_enrol, same_face


def _person(root, label: str, n: int, seed: int, reason: str = "test",
            also=(), allow_shrink: bool = True) -> int:
    """Write one generation holding ``label`` (and optionally more people).

    ``also`` is a sequence of ``(label, n, seed)``. Returns the generation."""
    g = FaceGallery(root=root)
    for vec in same_face(base_vec(seed), n, seed=seed + 1):
        g.add(label, vec)
    for other, count, oseed in also:
        for vec in same_face(base_vec(oseed), count, seed=oseed + 1):
            g.add(other, vec)
    return g.save(reason=reason, allow_shrink=allow_shrink)


def _counts(root, generation: int) -> dict:
    """{label: samples} in one generation, read straight off the disk."""
    one = FaceGallery(root=root)
    if not one.load(generation=generation):
        return {}
    return {label: one.count(label) for label in one.labels()}


# ------------------------------------------------- route 1: the prune route
def test_a_bystander_is_not_pruned_out_of_existence_by_the_delete_s_own_save(
        tmp_path):
    """ROUTE 1, DIRECTION (a): nobody else loses anything.

    ``purge_label`` calls ``save()``, and ``save()`` ends in ``_prune()``,
    which drops the oldest generations outside the five-deep window. Alice's
    only generation is the oldest one, and she is in NO generation this delete
    is even looking at -- so nothing in the purge loop ever considers her, and
    nothing in it notices her file going.

    Reproduced on today's code, 2026-09-03: five generations (alice's, then
    four holding hunter and heather), ``purge_label("heather")`` ->
    ``gen-00001.npz`` shredded by ``_prune``, alice's six embeddings gone,
    ``complete`` True. The delete reported success over a destroyed
    enrolment that had nothing to do with it."""
    root = tmp_path / "g"
    alice = _person(root, "alice", 6, seed=41)
    for i in range(4):
        _person(root, "hunter", 6, seed=11,
                also=(("heather", 6, 71),), reason="both %d" % i)
    assert FaceGallery(root=root).generations() == [1, 2, 3, 4, 5]

    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert (root / ("gen-%05d.npz" % alice)).exists(), \
        "the delete's own prune destroyed a bystander's only generation"
    assert _counts(root, alice) == {"alice": 6}
    assert out["complete"] is True
    for gen in FaceGallery(root=root).generations():
        assert "heather" not in _counts(root, gen)


# ------------------------------------------ route 2: samples, not just names
def test_a_bystander_may_not_lose_samples_with_the_delete_called_complete(
        tmp_path):
    """ROUTE 2, DIRECTION (a): the guard was LABEL-level.

    The old proof asked "is hunter in the new generation?" and hunter was, so
    the generation holding ten of his takes was destroyed on the strength of a
    generation holding three. He keeps his name and loses seven samples, and
    the command says the delete was complete.

    A name is not an enrolment. The inventory proves COUNTS."""
    root = tmp_path / "g"
    _person(root, "hunter", 10, seed=11, also=(("heather", 4, 71),))
    _person(root, "hunter", 3, seed=11, also=(("heather", 4, 71),),
            reason="a shrunken save")

    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert _counts(root, 1) == {"hunter": 10, "heather": 4}, \
        "ten of his takes were destroyed to prove three of them exist"
    assert out["not_carried"] == [1]
    assert out["complete"] is False, \
        "she is still in generation 1 and was told she was gone"
    assert out["still_holding"] == [1]


# ------------------------------- route 3: a generation that yields no vectors
def test_a_generation_that_holds_her_but_yields_no_vectors_is_not_invisible(
        tmp_path):
    """ROUTE 3, DIRECTION (b): she was told she was gone while she was not.

    ``purge_label``'s scan used ``_read``, which yields VECTORS -- and a
    generation written by a model this build has never heard of yields none
    at all (``_read`` refuses to validate vectors it cannot size). Her four
    embeddings sat in a file whose keys name her, the scan saw an empty pool,
    the early return fired, and ``complete`` came back True.

    The inventory is a RAW key read at the same FORMAT, so a label in a file
    is a label in the file whatever wrote it. Nothing else in that generation
    is anybody else's, so it goes."""
    root = tmp_path / "g"
    _person(root, "hunter", 6, seed=11)
    hers = FaceGallery(root=root)
    for vec in same_face(base_vec(71), 4, seed=72):
        hers.add("heather", vec)
    gen = hers.save(reason="hers", allow_shrink=True)
    data = dict(np.load(root / ("gen-%05d.npz" % gen)))
    data["_model"] = np.array(["a_model_this_build_never_heard_of"])
    np.savez(root / ("gen-%05d.npz" % gen), **data)

    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert gen in out["generations_with"], "her file was invisible to the scan"
    assert not (root / ("gen-%05d.npz" % gen)).exists()
    assert out["complete"] is True
    assert _counts(root, 1) == {"hunter": 6}
    for path in root.iterdir():
        assert b"heather" not in path.read_bytes()


def test_a_foreign_generation_holding_her_AND_him_is_left_and_reported(
        tmp_path):
    """ROUTE 3, the other half. The same unreadable-by-us generation, with a
    bystander in it: now it may not go, because nothing here can carry him
    forward -- and she is still on the disk, so ``complete`` is False."""
    root = tmp_path / "g"
    both = _person(root, "hunter", 6, seed=11, also=(("heather", 4, 71),))
    data = dict(np.load(root / ("gen-%05d.npz" % both)))
    data["_model"] = np.array(["a_model_this_build_never_heard_of"])
    np.savez(root / ("gen-%05d.npz" % both), **data)

    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert (root / ("gen-%05d.npz" % both)).exists()
    assert out["foreign"] == [both]
    assert out["removed"] == 0
    assert out["complete"] is False
    assert out["still_holding"] == [both]


# ------------------------------------ the invariant itself: a REAL read-back
def test_a_save_that_did_not_land_destroys_nothing(tmp_path, monkeypatch):
    """THE INVARIANT, DIRECTION (a). The proof may not be the return value.

    Here ``save`` returns a generation number, raises nothing, and writes a
    file holding two of hunter's six takes -- a partial write, a truncated
    disk, a bug in a future save path. Every earlier version of this code
    proved the survivors from ``self.labels()``, which is MEMORY, and would
    shred the generation holding all six.

    Reading the replacement back from the disk is the only thing that can
    tell those two apart."""
    root = tmp_path / "g"
    _person(root, "hunter", 6, seed=11, also=(("heather", 4, 71),))

    def half_a_save(self, reason="", allow_shrink=False, **kw):
        gen = (self.generations() or [0])[-1] + 1
        arrays = {"emb_hunter_%04d" % i: v
                  for i, v in enumerate(self.embeddings("hunter")[:2])}
        arrays["_format"] = np.array([1])
        arrays["_created_ns"] = np.array([0])
        arrays["_reason"] = np.array([str(reason)])
        arrays["_model"] = np.array([str(self.model)])
        np.savez(self.path_for(gen), **arrays)
        return gen

    monkeypatch.setattr(FaceGallery, "save", half_a_save)
    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert out["removed"] == 0
    assert out["complete"] is False
    assert _counts(root, 1) == {"hunter": 6, "heather": 4}


def test_the_delete_that_can_be_proved_still_happens(tmp_path):
    """THE CONTROL. None of the above may make an ordinary delete timid: the
    survivors ARE in the new generation, so the old ones go."""
    root = tmp_path / "g"
    _person(root, "hunter", 6, seed=11, also=(("heather", 4, 71),))
    _person(root, "hunter", 6, seed=11, also=(("heather", 4, 71),),
            reason="again")

    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert out["removed"] == 2
    assert out["complete"] is True
    assert out["still_holding"] == []
    assert out["labels_left"] == ("hunter",)
    back = FaceGallery(root=root)
    assert back.load() is True and back.count("hunter") == 6
    for path in root.iterdir():
        assert b"heather" not in path.read_bytes()


def test_a_generation_that_could_not_be_shredded_is_not_called_complete(
        tmp_path, monkeypatch):
    """DIRECTION (b), through the last step. The proof passed, the shred
    failed, and the file is still there holding her. ``complete`` is False
    because the disk is read AFTER the shredding, not because a return value
    was checked."""
    root = tmp_path / "g"
    _person(root, "hunter", 6, seed=11, also=(("heather", 4, 71),))
    import jarvis.facegallery as fg

    def no_shred(path):
        raise OSError("read-only filesystem")

    monkeypatch.setattr(fg, "_shred", no_shred)
    out = FaceGallery(root=root).purge_label("heather", reason="test")

    assert out["removed"] == 0
    assert out["complete"] is False
    assert out["still_holding"] == [1]
    assert _counts(root, 1) == {"hunter": 6, "heather": 4}


# ------------------------------------------- the two smaller ones this round
def test_the_nothing_enrolled_line_names_who_IS_on_the_disk(tmp_path, capsys):
    """It read the labels off a gallery that had loaded NOTHING.

    A store written by another model refuses to load into this one -- by
    design -- so ``gallery.labels()`` is empty and the line printed
    "(labels: -)" over a full enrolment sitting right there. The names come
    off the disk now, raw, the same way the inventory finds her."""
    root = tmp_path / "g"
    old = FaceGallery(root=root, model="sface")
    for vec in same_face(base_vec(11), 6, seed=12):
        old.add("hunter", vec)
    old.save(reason="his sface enrolment")

    class Args:
        label = "heather"
        yes = True
        json = False

    lines = []
    gallery = FaceGallery(root=root, model="arcface_mbf")
    code, _out = face_enrol.do_delete_label(gallery, "heather", Args(),
                                            lines.append)
    text = "\n".join(lines)
    assert code == 3, text
    assert "hunter" in text, text
    assert "labels: -" not in text


def test_the_voice_gallery_survives_a_config_that_cannot_answer(monkeypatch):
    """``_face_gallery`` read the config with no guard at all, while its
    sibling ``_face_owner`` has one. A raising config service -- or a typo in
    ``camera.face_backend``, which ``backend_for`` refuses BY DESIGN -- took
    the whole voice path down with a traceback.

    It may not guess a model either: opening the default gallery over a store
    another model wrote is how "who do you recognise" answers "nobody" over a
    live enrolment. So it returns None and the command says so."""
    from jarvis import commander as cm

    class Raises:
        def get(self, key, default=None):
            raise RuntimeError("the config service is down")

    class Typo:
        def get(self, key, default=None):
            return "insighface" if key == "camera.face_backend" else default

    class Ctx:
        def __init__(self, cfg):
            self.cfg = cfg

        def _svc(self, name):
            return self.cfg if name == "assistant" else None

    assert cm._face_gallery(Ctx(Raises())) is None
    assert cm._face_gallery(Ctx(Typo())) is None

    cmd = [c for c in cm.ASSISTANT_TIER1 if c.name == "face gallery"][0]
    text = "who do you recognise"
    out = cmd.handler(Ctx(Typo()), text, cmd.matcher(text))
    assert out.handled and out.speak
    assert "face_backend" in out.reply
